dictionaries = []
words = [
    "abl",
    "athletik",
    "athletisme",
    "athlétisme",
    "atirar",
    "atletica",
    "atletismo",
    "atribute",
    "att",
    "beforeend",
    "behaviour",
    "betterrolls",
    "brsw",
    "bugfix",
    "combattere",
    "desentrenada",
    "disparar",
    "dmg",
    "druidenmagie",
    "druidisme",
    "dsn",
    "elementalism",
    "elementalisme",
    "elementarmagie",
    "entraine",
    "entrainé",
    "etrange",
    "fas",
    "foi",
    "fokus",
    "gangup",
    "gesangsmagie",
    "globals",
    "heahmagie",
    "heahwisardry",
    "hechiceria",
    "hechicería",
    "hekau",
    "hotbar",
    "hrimmagie",
    "hrimwisardry",
    "khe",
    "kämpfen",
    "lbt",
    "lutar",
    "magie",
    "mathemagic",
    "mbt",
    "modifers",
    "namespaced",
    "non",
    "npc",
    "optinal",
    "pelear",
    "popout",
    "popouts",
    "powerpoints",
    "preloaded",
    "psionica",
    "psiónica",
    "rerolls",
    "rof",
    "sbt",
    "sha'ir",
    "solaire",
    "sparare",
    "spellcasting",
    "succ",
    "swade",
    "swcone",
    "swd",
    "tir",
    "twbr",
    "undead",
    "unshake",
    "unstun",
    "untrainiert",
    "ushabti",
    "vehicle_actor",
    "vehicle_actor_id",
    "voidomancy",
    "weblate",
    "wizir",
    "zaubern",
    "élémentalisme",
    "étrange",
]
flag_words = []
ignore_paths = []
ignore_patterns = []
use_global = true
