dictionaries = []
words = [
    "abl",
    "atribute",
    "att",
    "behaviour",
    "betterrolls",
    "brsw",
    "dmg",
    "dsn",
    "fas",
    "globals",
    "hotbar",
    "modifers",
    "namespaced",
    "npc",
    "optinal",
    "popout",
    "popouts",
    "preloaded",
    "rerolls",
    "swade",
    "swd",
    "undead",
    "unshake",
    "unstun",
    "vehicle_actor",
    "vehicle_actor_id",
]
flag_words = []
ignore_paths = []
