dictionaries = []
words = [
    "abl",
    "atribute",
    "att",
    "behaviour",
    "betterrolls",
    "brsw",
    "bugfix",
    "dmg",
    "dsn",
    "fas",
    "gangup",
    "globals",
    "hotbar",
    "modifers",
    "namespaced",
    "npc",
    "optinal",
    "popout",
    "popouts",
    "preloaded",
    "rerolls",
    "succ",
    "swade",
    "swd",
    "undead",
    "unshake",
    "unstun",
    "vehicle_actor",
    "vehicle_actor_id",
    "weblate",
    "kämpfen",
    "pelear",
    "lutar",
    "combattere",
    "disparar",
    "tir",
    "atirar",
    "sparare",
    "athletik",
    "atletismo",
    "athletisme",
    "athlétisme",
    "atletica",
]
flag_words = []
ignore_paths = []
