name: Update Wiki

on:
  workflow_dispatch:
    paths:
      - 'docs/**'
    branches:
      - version_2

  push:
    paths:
      - 'docs/**'
    branches:
      - version_2
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
    - uses: OrlovM/Wiki-Action@v1
      with:
        path: 'docs'
        token: ${{ secrets.GITHUB_TOKEN }}